"""
em_report.py - PDF report generator using matplotlib's PdfPages.

Produces a multi-page PDF with:
  Page 1: cover + project summary
  Page 2: water surface profile chart (depth, EGL, invert vs station)
  Page 3: cavitation index chart (sigma vs station)
  Page 4: profile data table
  Page 5: cavitation data table
"""
from __future__ import annotations
import os
from typing import Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np

from em_data import GeometryFile
from em_ws77 import WS77Result


def make_pdf_report(g, res: WS77Result, output_path: str,
                     title: Optional[str] = None) -> str:
    """Generate a multi-page PDF report of a WS77 run.

    g: GeometryFile (input)
    res: WS77Result (computed profile)
    output_path: path to .pdf file
    """
    rows = res.rows
    if not rows:
        raise ValueError("No profile rows to report")

    sta = [r["sta"] for r in rows]
    invert = [r["invert"] for r in rows]
    depth = [r["depth"] for r in rows]
    egl = [r["egl"] for r in rows]
    vel = [r["velocity"] for r in rows]
    sigma = [r["sigma"] for r in rows]
    ws = [r["invert"] + r["depth"] for r in rows]

    pdf = PdfPages(output_path)
    fig_w, fig_h = 11, 8.5

    # Page 1: cover
    fig = plt.figure(figsize=(fig_w, fig_h))
    fig.suptitle("EM-Py Cavitation Analysis Report", fontsize=20, fontweight="bold", y=0.95)
    plt.figtext(0.1, 0.85, f"Project: {g.title}", fontsize=14)
    plt.figtext(0.1, 0.81, f"Discharge Q = {g.q:.3f} m³/s  ({g.q * 35.3147:.1f} cfs)", fontsize=12)
    plt.figtext(0.1, 0.78, f"Initial depth y₀ = {g.y0:.3f} m", fontsize=12)
    plt.figtext(0.1, 0.75, f"Stations analyzed: {len(g.stations)}", fontsize=12)
    plt.figtext(0.1, 0.72, f"Initial EGL = {res.egl_initial:.3f} m", fontsize=12)
    plt.figtext(0.1, 0.69, f"Manning's k_s = {g.k_s * 1000:.2f} mm", fontsize=12)
    if hasattr(g, "label") and g.label:
        plt.figtext(0.1, 0.66, f"Description: {g.label}", fontsize=12)
    plt.figtext(0.1, 0.55, "This report was generated by EM-Py v0.4,\n"
                "a modern Python port of the U.S. Bureau of Reclamation\n"
                "'Cavitation Programs' toolset by Henry T. Falvey (1987/1990).",
                fontsize=11, style="italic")
    plt.figtext(0.1, 0.4, "Algorithms applied:\n"
                "  • Standard step water surface profile (WS77)\n"
                "  • 1/7-power-law boundary layer integration\n"
                "  • Cavitation index calculation\n"
                "  • Bélanger hydraulic jump detection\n"
                "  • Damage index fit (USBR criteria)",
                fontsize=11)
    plt.figtext(0.1, 0.18, f"Run date: {__import__('datetime').datetime.now():%Y-%m-%d %H:%M}",
                fontsize=10, style="italic")
    plt.axis("off")
    pdf.savefig(fig)
    plt.close(fig)

    # Page 2: profile chart
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.plot(sta, invert, "k-", lw=2, label="Invert")
    ax.plot(sta, ws, "b-", lw=2, label="Water surface")
    ax.plot(sta, egl, "r--", lw=1.5, label="EGL")
    ax.fill_between(sta, invert, ws, color="blue", alpha=0.1, label="Flow")
    ax.set_xlabel("Station (m)")
    ax.set_ylabel("Elevation (m)")
    ax.set_title("Water Surface Profile", fontsize=14)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")
    pdf.savefig(fig)
    plt.close(fig)

    # Page 3: velocity + cavitation
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(fig_w, fig_h), sharex=True)
    ax1.plot(sta, vel, "g-", lw=2)
    ax1.set_ylabel("Velocity (m/s)")
    ax1.set_title("Velocity Profile", fontsize=13)
    ax1.grid(True, alpha=0.3)
    ax2.plot(sta, sigma, "m-", lw=2, label="σ (flow)")
    ax2.axhline(y=0.2, color="r", linestyle="--", label="Critical σ = 0.2")
    ax2.set_xlabel("Station (m)")
    ax2.set_ylabel("Cavitation index σ")
    ax2.set_title("Cavitation Index", fontsize=13)
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc="best")
    pdf.savefig(fig)
    plt.close(fig)

    # Page 4: profile table
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.axis("off")
    headers = ["STA", "Invert", "Depth", "V", "EGL", "Profile", "σ"]
    cell_data = [[f"{r['sta']:.1f}", f"{r['invert']:.2f}", f"{r['depth']:.3f}",
                   f"{r['velocity']:.2f}", f"{r['egl']:.2f}", r['profile'],
                   f"{r['sigma']:.3f}"]
                  for r in rows]
    tbl = ax.table(cellText=cell_data, colLabels=headers, loc="center", cellLoc="right")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8)
    tbl.scale(1, 1.2)
    ax.set_title("Profile Data", fontsize=14, fontweight="bold")
    pdf.savefig(fig)
    plt.close(fig)

    # Page 5: cavitation data
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.axis("off")
    cav_headers = ["STA", "V", "σ", "Chamfer 1:4", "Chamfer 1:2", "Chamfer 1:1"]
    cav_rows = [[f"{r['sta']:.1f}", f"{r['velocity']:.2f}", f"{r['sigma']:.3f}",
                  f"{r['damage_1_4']:.4f}", f"{r['damage_1_2']:.4f}", f"{r['damage_1']:.4f}"]
                 for r in rows]
    cav_tbl = ax.table(cellText=cav_rows, colLabels=cav_headers, loc="center", cellLoc="right")
    cav_tbl.auto_set_font_size(False)
    cav_tbl.set_fontsize(8)
    cav_tbl.scale(1, 1.2)
    ax.set_title("Cavitation and Chamfer Damage Rates", fontsize=14, fontweight="bold")
    pdf.savefig(fig)
    plt.close(fig)

    pdf.close()
    return output_path


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(__file__))
    from em_data import read_geometry_file, read_ws_output
    g = read_geometry_file("sample_data/DATA/GLENIN")
    ref = read_ws_output("sample_data/DATA/GLENOUT")
    from em_ws77 import compute_profile
    res = compute_profile(g, egl_calibration=ref.egl_initial)
    out = make_pdf_report(g, res, "/tmp/ws77_report.pdf")
    print(f"Generated: {out}")
